export const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_ERROR = 'FETCH_POSTS_ERROR';
export const POSTS_PAGE_CHANGE = 'POSTS_PAGE_CHANGE';
export const POSTS_FILTER_CHANGE = 'POSTS_FILTER_CHANGE';
